services:
  blog-backend:
    image: amazoncorretto:21
    container_name: blog_backend
    restart: always
    ports:
      - "80:8084"
    working_dir: /app
    volumes:
      - ./build/:/app/build/
      - ./logs/:/app/logs/
    environment:
      - secretKey=${SECRET_KEY}
    command: ["java", "-jar", "build/app.jar", "--spring.profiles.active=${SPRING_PROFILE}"]