routes:
# 글 저장
- path: "/api/posts"
  method: "POST"
# 글 수정
- path: "/api/posts/\\d+"
  method: "PUT"
# 글 삭제
- path: "/api/posts/\\d+"
  method: "DELETE"
# 파일 다운로드
- path: "/api/attachment/download/\\d+"
  method: "GET"
# 카테고리 상세 조회
- path: "/api/categories/detail"
  method: "GET"
# 카테고리 저장
- path: "/api/categories"
  method: "POST"