spring:
  datasource:
    url: ENC(oGZYIdSbF8rGvE5F0kmDpONR55amrQJLRiOPdHZVSztEIWmODysO1HaxiG5ddODUPIvxFl5RXaA=)
    username: ENC(tGdDB47nYga+OIFSXo14tA==)
    password: ENC(flOZMKguakXucoO85HWVFg==)
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: ENC(aUBTr3LoTufYc9tIjIL17Dgr1GsSNVQOAu/aEPWEWV3Si6bgDMm7+ACE9gtoralNTnyrdwOIcws=)