spring:
  datasource:
    url: ENC(xhPQ3Qqy63xBwsylN6ZzTc5NYC+39ZwWaV9r4lzLbsx3YHomdrKalSlUOKW5mK+A)
    username: ENC(x7lfRtqZ8ilkQauaGSRlKA==)
    password: ENC(LGEIdglyyZZkkfcj3jz/oQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: ENC(ZR87xZE3yunC2Fg5yabMN6tvrkortYMh6R1tyO6fOUue83E6LOrQzEZ+VlSaJlHxWYYKj2mLACo=)