spring:
  datasource:
    url: ENC(jg6ykjc4wF8hr8xqUzJvWIXzkhh29J2STsQNW4bkVxQf8III2uDNqtW8i4jat4Sz)
    username: ENC(tGdDB47nYga+OIFSXo14tA==)
    password: ENC(flOZMKguakXucoO85HWVFg==)
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: ENC(aUBTr3LoTufYc9tIjIL17Dgr1GsSNVQOAu/aEPWEWV3Si6bgDMm7+ACE9gtoralNTnyrdwOIcws=)