CREATE TABLE tbl_member (
    member_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1;